AWSDB:
  apiVersion: "2012-08-10"
  region: "us-east-1"
  endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  accessKeyId: "AKIA56LNNCUPJ4GO3LP4"
  secretAccessKey: "qdFfvWb+/FeBCidXRCQUma/KRC22bL52Ryqz46zE"

JWT:
  jwt_secret: "your_jwt_secret"

ADMIN:
  id: 0
  login: "admin"
  pass: "$2b$10$VfijFYxd7lZKPugQuWhuN.djUpUBlgVgE.JbyC1.BTlxuhhoMH8j2"

BCRYPT:
  saltRounds: 10

